In [1]:
import numpy as np

In [2]:
v=[1,2,3,4]
v1=np.array([1,2,3,4])

In [4]:
v.shape

AttributeError: 'list' object has no attribute 'shape'

In [5]:
v1.shape

(4,)

In [7]:
M=np.array([[1,2],[2,4]])

In [8]:
print(M)

[[1 2]
 [2 4]]


In [9]:
np.shape(M)

(2, 2)

In [10]:
M.shape

(2, 2)

$\begin{pmatrix}
1&2&3\\
4&5&6
\end{pmatrix}
$

In [11]:
M1=np.array([[1,2,3],[4,5,6]])

In [12]:
np.shape(M1)

(2, 3)

In [13]:
print("El número de filas es {0} el número de columnas es {1}".format(np.shape(M1)[0],np.shape(M1)[1]))

El número de filas es 2 el número de columnas es 3


In [14]:
M1[0,1]

2

Práctica 1
* filas van a ser el penultimo número de tu DNI/NIE

* columas van a ser el segundo número de tu DNI/NIE

* rellenaremos esa matriz con ceros

In [18]:
np.empty([5,4])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306],
       [4.45060607e-308, 1.78020848e-306, 7.56587585e-307,
        1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        8.01097889e-307],
       [1.69119873e-306, 1.60219306e-306, 8.34451504e-308,
        8.34402698e-308]])

In [19]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
## Matriz Identidad
### I_5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# A*I=A=I*A

In [26]:
A=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [27]:
np.shape(A)

(2, 5)

In [28]:
B=np.array([1,2,3,4])

In [29]:
### Sumar y restar

In [30]:
A+B

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [31]:
C=np.array([5,6,7,8])

In [32]:
B+C

array([ 6,  8, 10, 12])

In [33]:
C+B

array([ 6,  8, 10, 12])

In [34]:
C+B==B+C

array([ True,  True,  True,  True])

In [35]:
C-B

array([4, 4, 4, 4])

In [36]:
B-C

array([-4, -4, -4, -4])

In [37]:
D=np.array([[5,6,7,8,9],[0,1,2,3,4]])

In [38]:
A+D

array([[ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13]])

In [39]:
A-D

array([[-5, -5, -5, -5, -5],
       [ 5,  5,  5,  5,  5]])

In [40]:
A*C

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [41]:
B*C

array([ 5, 12, 21, 32])

In [42]:
B

array([1, 2, 3, 4])

In [43]:
C

array([5, 6, 7, 8])

In [44]:
A*D

array([[ 0,  6, 14, 24, 36],
       [ 0,  6, 14, 24, 36]])

In [45]:
A/D

C:\Users\Daniel Montes\AppData\Local\Temp\ipykernel_5696\1827223143.py:1: RuntimeWarning: divide by zero encountered in true_divide
  A/D


array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [       inf, 6.        , 3.5       , 2.66666667, 2.25      ]])

$A=\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix}$

$B=\begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix}$

$A_{n\times m}$
$B_{m \times p}$

$\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix} \times \begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix}$

$\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix} \times \begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix} = 
\begin{pmatrix}
1\times 3 + 2 \times 7 & 1 \times 5 + 2\times 6 \\
 9\times 3 + 4 \times 7 & 9 \times 5 + 4\times 6
\end{pmatrix}
$

In [46]:
A @ D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

In [47]:
A.shape

(2, 5)

In [49]:
D.shape

(2, 5)

In [51]:
D

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [50]:
D.T

array([[5, 0],
       [6, 1],
       [7, 2],
       [8, 3],
       [9, 4]])

In [52]:
A@D.T

array([[ 80,  30],
       [255,  80]])

In [53]:
D.T@A

array([[ 0,  5, 10, 15, 20],
       [ 5, 12, 19, 26, 33],
       [10, 19, 28, 37, 46],
       [15, 26, 37, 48, 59],
       [20, 33, 46, 59, 72]])

In [54]:
A*D

array([[ 0,  6, 14, 24, 36],
       [ 0,  6, 14, 24, 36]])

In [55]:
A/D

C:\Users\Daniel Montes\AppData\Local\Temp\ipykernel_5696\1827223143.py:1: RuntimeWarning: divide by zero encountered in true_divide
  A/D


array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [       inf, 6.        , 3.5       , 2.66666667, 2.25      ]])

$A^{-1}$

$y=A \times x$

$y/A=x$

$ A^{-1}\times y = x $


$A \times B = I = B \times A$

In [58]:
np.invert(A)

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10]], dtype=int32)

In [59]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

In [62]:
np.linalg.inv(A@D.T)

array([[-0.064,  0.024],
       [ 0.204, -0.064]])

In [63]:
np.linalg.inv(A@D.T)@(A@D.T)

array([[1., 0.],
       [0., 1.]])

Ejemplo 2

En una granja hay gallinas y cerdos
si cuento las patas hay 120 patas
si cuento las cabezas 50 cabezas

2 G + 4 C = 120

G+C=50

$\begin{pmatrix}
2 G + 4C \\
G+C
\end{pmatrix} = \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

$\begin{pmatrix}
2 & 4  \\
1 & 1
\end{pmatrix} \begin{pmatrix} G \\ C \end{pmatrix} = \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

$ \begin{pmatrix} G \\ C \end{pmatrix} = \begin{pmatrix}
2 & 4  \\
1 & 1
\end{pmatrix}^{-1} \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

In [64]:
A=np.array([[2,4],[1,1]])

In [65]:
np.linalg.inv(A)

array([[-0.5,  2. ],
       [ 0.5, -1. ]])

In [66]:
np.linalg.inv(A)@np.array([120,50])

array([40., 10.])

In [67]:
np.linalg.inv(A)@np.array([120,51])

array([42.,  9.])

In [68]:
B=np.array([[2,4],[1,2]])

In [69]:
np.linalg.inv(B)@np.array([120,50])

LinAlgError: Singular matrix

In [70]:
B

array([[2, 4],
       [1, 2]])

* SCD $\to$ Sistema Compatible Determinado $\to$ el sistema tiene unica solución
* SCI $\to$ Sistema Compatible Indeterminado $\to$ el sistema tiene infinita soluciones
* SI $\to$ Sistema Incompatible  $\to$ No tiene solución

In [71]:
np.linalg.solve(A,np.array([120,50]))

array([40., 10.])

In [72]:
np.linalg.solve(B,np.array([120,50]))

LinAlgError: Singular matrix

In [73]:
A.dtype

dtype('int32')

In [74]:
A

array([[2, 4],
       [1, 1]])

In [75]:
2*A

array([[4, 8],
       [2, 2]])

In [76]:
A/2

array([[1. , 2. ],
       [0.5, 0.5]])

In [77]:
0.5*A

array([[1. , 2. ],
       [0.5, 0.5]])

## Ejercicio 4
Resolver el sistema y que muestre por pantalla las soluciones al sistema

$x-3y+2z-w=6$

$2x-4y+5z+2w=13$

$-x+3y-z+3w=-23$

$3x+2y-z-w=6$

x=?? y=?? z=?? w=??

In [2]:
import numpy as np

A = np.array([[1,-3,2,-1],[2,-4,5,2],[-1,3,-1,3],[3,2,-1,-1]])

# A * X = B
# X = (A).inv * B

B = np.array([6,13,-23,6])

solution = np.linalg.solve(A,B).round()

print(f"El resultado es el siguiente, X = {solution[0]}, Y = {solution[1]}, Z = {solution[2]} y W = {solution[3]}")

El resultado es el siguiente, X = -25.0, Y = 55.0, Z = 75.0 y W = -46.0
